name: Auto-Release

on: 
  push:
    tags: 
    - '*.*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd #v1.12.0
      with:
        tag: ${{ inputs.version || github.ref_name }}
        artifacts: "./Assemblies.zip"
        body: |
          This release contains the assemblies of Resonite version ${{ inputs.version || github.ref_name}}.