name: Auto-Release

on: 
  push:
    branches: 
    - main
    paths:
    - 'Assemblies/**'
    - 'Assemblies.zip'
    - '.github/workflows/**'
    - 'get-resonite-version.csx'
  workflow_dispatch:
    inputs:
      version:
        description: Version Override
        required: false
        type: string
env:
  ResonitePath: Assemblies

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 #v5.2.0
      with:
        dotnet-version: '10'
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - name: Extract Resonite version
      id: extract_version
      run: |
        dotnet tool install -g dotnet-script || exit $?
        RESONITE_VERSION="$(dotnet script get-assembly-version.csx Assemblies/FrooxEngine.dll)" || exit $?
        echo "resonite_version=$RESONITE_VERSION" >> "$GITHUB_OUTPUT" || exit $?
        echo "Detected Resonite version: $RESONITE_VERSION"
    - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd #v1.12.0
      with:
        tag: ${{inputs.version || steps.extract_version.outputs.resonite_version}}
        artifacts: "./Assemblies.zip"
        makeLatest: true
        allowUpdates: true
        body: |
          This release contains the assemblies of Resonite version ${{steps.extract_version.outputs.resonite_version}}.